# Syntax highlighting
highlightstyle: ''
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
highlighter: null
# - markdown: kramdown

title: "Jarrod Whaley"
tagline: ""
description: "Follow <a href=\"https://micro.blog/jbwhaley\">@jbwhaley on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/jbwhaley\">@jbwhaley on Micro.blog</a>."
baseurl: ""
url: "http://www.jarrodwhaley.com"
markdown: "kramdown"
username: "jbwhaley"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Jarrod Whaley"
name: "Jarrod Whaley"
gravatar_hash: "eb39abb44dcd60816652e95a3e8e7f89"
avatar: "https://www.gravatar.com/avatar/eb39abb44dcd60816652e95a3e8e7f89?s=160"
full_name: "Jarrod Whaley"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Pacific-New"